### ISSUE TITLE
Readme bug

### ISSUE THREAD

**Issue by edd** [vegaprotocol/Public_Test_Bridge_Tools#4]
> All of these tokens are whitelisted to the Vega ERC20 Bridge listed above. They all also have the faucet() function.

This is flagrantly false for two reasons:

- The bridges are listed below this line, not above it
- The tokens are not all whitelisted on the bridges listed _below_.

# Tasks
- [ ] Replace 'above' with 'below'
- Either
    - [ ] Add all assets to whitelist on all bridge contracts, or
    - [ ] Remove that line
